###
### Gateway
###
apiVersion: gateway.githedgehog.com/v1alpha1
kind: GatewayGroup
metadata:
  name: default
  namespace: default
spec: {}
---
apiVersion: gateway.githedgehog.com/v1alpha1
kind: Gateway
metadata:
  name: gateway-1
  namespace: default
spec:
  interfaces:
    enp2s1: {}
  workers: 16
---
apiVersion: gateway.githedgehog.com/v1alpha1
kind: Gateway
metadata:
  name: gateway-2
  namespace: default
spec:
  interfaces:
    enp2s1: {}
  workers: 16
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: ds4000-01--gateway--gateway-1
spec:
  gateway:
    links:
      - gateway:
          port: gateway-1/enp2s1
        switch:
          port: ds4000-01/E1/20/1
---
apiVersion: wiring.githedgehog.com/v1beta1
kind: Connection
metadata:
  name: ds4000-02--gateway--gateway-2
spec:
  gateway:
    links:
      - gateway:
          port: gateway-2/enp2s1
        switch:
          port: ds4000-02/E1/20/1
