set shell := ["bash", "-euo", "pipefail", "-c"]

update-diagrams:
	@echo "==============================================="
	@echo "Updating diagrams for env-ci-1.l"
	@echo "==============================================="

	@echo "Generating diagrams for env-ci-1.l: spine-leaf"
	mkdir -p env-ci-1.l/diagrams/spine-leaf
	hhfab init --dev -f -w env-ci-1.l/wiring.yaml
	hhfab diagram --format drawio --style default --output env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf.drawio
	hhfab diagram --format drawio --style cisco --output env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf-cisco.drawio
	hhfab diagram --format drawio --style hedgehog --output env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf-hedgehog.drawio
	hhfab diagram --format dot    --output env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf.dot
	hhfab diagram --format mermaid --output env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf.mermaid
	if command -v dot >/dev/null; then dot -Tsvg -Gbgcolor=transparent env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf.dot -o env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf.dot.svg; fi
	if command -v drawio >/dev/null; then drawio --export --format svg --output env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf.default.drawio.svg env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf.drawio; fi
	if command -v drawio >/dev/null; then drawio --export --format svg --output env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf.cisco.drawio.svg env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf-cisco.drawio; fi
	if command -v drawio >/dev/null; then drawio --export --format svg --output env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf.hedgehog.drawio.svg env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf-hedgehog.drawio; fi
	if command -v mmdc >/dev/null; then mmdc -i env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf.mermaid -o env-ci-1.l/diagrams/spine-leaf/env-ci-1-spine-leaf.mermaid.svg -t default -b transparent; fi

	@echo ""
	@echo "All diagrams updated for env-ci-1.l"

	@just create-html

create-html: _check-go
	@go run ${FABRICATOR_PATH:-../../fabricator}/hack/generate_viewer.go --dirs "env-ci-1.l/diagrams" --output-dir . --output-file diagram-viewer.html

_check-go:
	@command -v go >/dev/null 2>&1 || (echo "Go not installed. Install from https://golang.org" && exit 1)

default: update-diagrams
